# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b87cf419bcd8e01f87a2d9cffd90a46e57375abcde8e632a6838b44df3b7928df89ea6ba76a4d4ac360ac75504cdae1a981d433c4c7c763a1684f4268ad8e018

test:
  secret_key_base: 278a22b0bdf96cc63a9bf11fac48424986b0993e039116449f155840c4db0a73132c2a804e7a6e90759944d6842afc288d5bc318df8545f0d98a9a5b78b59f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
